name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        repository: 'kapilkumaria/DevSecOps-CI-pipeline-with-github-actions-sonarqube-trivy-and-jfrog'
        ref: 'master'

    # Step 2: Set up Java and Maven
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    # Step 3: Build the project using Maven (pre-installed)
    - name: Build the package
      run: mvn -B -DskipTests clean package

    # Step 4: Run tests
    - name: Run tests
      run: mvn test
    